#NAME: Jonathan Chon
#EMAIL: jonchon@gmail.com
#ID: 104780881

CC = gcc
FLAGS = -Wall -Wextra

default:
	@$(CC) $(FLAGS) lab1a.c -o lab1a

clean:
	@rm -f lab1a *.tar.gz

dist:
	@tar -czf lab1a-104780881.tar.gz Makefile README lab1a.c
